### ISSUE TITLE
Package broken with atom 1.25

### ISSUE THREAD

**Issue by PierreMarchand20** [Aerijo/autocomplete-latex#13]
The last update broke the package, I tried to rebuild it and to reinstall it without success.

**Comment by Aerijo** [comment]
What went wrong? I've been using it on the beta without issue (but then, my version is modified with unreleased changes).

Any error messages would help.

**Comment by PierreMarchand20** [comment]
Well it said that it was built on old core packages and needed to be rebuilt. I tried but it did not work so I uninstalled and tried to reinstalled the package without success

**Comment by PierreMarchand20** [comment]
here's the log when I try to reinstall : 
Installing “autocomplete-latex@0.8.3” failed.Hide output…

> oniguruma@6.2.1 install /private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9/node_modules/autocomplete-latex/node_modules/oniguruma
> node-gyp rebuild

/private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9
`-- (empty)


npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
gyp ERR! configure error 
gyp ERR! stack Error: Python executable "/Applications/Atom.app/Contents/Resources/app/apm/bin/python-interceptor.sh" is v3.6.4, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:454:14)
gyp ERR! stack     at /Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/configure.js:443:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:197:7)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:334:11)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at Socket.emit (events.js:188:7)
gyp ERR! stack     at Pipe._handle.close [as _onclose] (net.js:498:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9/node_modules/autocomplete-latex/node_modules/oniguruma
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9/package.json'
npm WARN apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9 No description
npm WARN apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9 No repository field.
npm WARN apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9 No README data
npm WARN apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9 No license field.
npm ERR! Darwin 16.7.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/pierremarchand/.atom/.apm/.apmrc" "--userconfig" "/Users/pierremarchand/.atom/.apmrc" "install" "/private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/d-118216-1223-13iukhi.036xgsnhfr/package.tgz" "--runtime=electron" "--target=1.7.11" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@6.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@6.2.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs oniguruma
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/83/5s8p7vm14l793szhdqbry8f40000gn/T/apm-install-dir-118216-1223-9c8nbs.8gwvasv2t9/npm-debug.log
npm ERR! code 1

**Comment by Aerijo** [comment]
Hmm. I just downloaded a fresh version of the package for Atom 1.26.0 beta, and it worked fine. I'm trying again now with the standard version.

In the meantime, try running `apm rebuild autocomplete-latex` in the command line and see if that helps.

**Comment by PierreMarchand20** [comment]
it gives me : Rebuilding modules ✓ but I still have the same output when I try to install the package

**Comment by Aerijo** [comment]
I don't get any problems on the stable version either. The `node-gyp` stuff looks suspicious though, I've had more than enough trouble with it in the past. Look at your PATH, and try removing any Python related additions.

**Comment by PierreMarchand20** [comment]
Ok my bad, I found the issue. I think it is because my command line python was linked to python 3.6 and it seems it is not supported according to the log. I think my package manager modified my command line because usually "python" is linked to the 2.7, anyway...
