### ISSUE TITLE
autocompletion of English not working

### ISSUE THREAD

**Issue by werunom** [Aerijo/autocomplete-latex#5]
I observed that after I enabled this package, the autocompletion of language (English) is not working. Disabled this package, and English prediction and predictions from the buffer of other opened files comes back :(

Can you fix this please? Thanks!

**Comment by werunom** [comment]
I also disabled `language-latex2e` and switched to the older language pack; the issue persists if the `autocomplete-latex` package is enabled.

**Comment by Aerijo** [comment]
Are you talking about the default completions that are taken from random words on the page?

That was intentionally disabled, but I'll add a setting to configure it.

**Comment by Aerijo** [comment]
BTW, I appreciate your help with identifying issues/improvements. It's difficult for me to do it myself, seeing as I might not run into, or even think of, a lot of issues. It's nice to have a different perspective on what should happen.

**Comment by werunom** [comment]
Yah...I am talking about the default completions. I use them quite often. 

Its my pleasure to assist in this way - given that you have taken time in cooking this package :)
